name: mis_labs
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  syncfusion_flutter_calendar: 20.3.49
  syncfusion_flutter_datepicker: 20.3.49
  cloud_firestore: ^4.3.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2
  firebase_database: ^10.0.8
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
